# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3a98f98e90352f0fb04518f5b6f718c0a322da45d2a42962086536fa5b4a28733b8b3519268b0e735c3f1eabc51fdad4eaaeb6fa37b2c1e563222665467a6ca

test:
  secret_key_base: 91bb9163e9f5bd2e5e40e75eb95c81fe2f67cc3b749be0b502162d8da915bca605a99d3a9970e748fe5e35b1cd6c278201d1dc71a0c9c2fa5270292866477edf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
